version: '3.9'
services:
  web:
    build:
      context: ./web
    container_name: multimodal-web
    restart: unless-stopped
    ports:
      - "10091:80"
  api:
    build: .
    container_name: multimodal-api
    ports:
      - "10090:10090"
    volumes:
      - ./data:/app/data
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant:v1.12.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
